export const ADDED_TODO='ADDED_TODO';
export const ADD_TODO_TOLOCALSTORAGE='ADD_TODO_TOLOCALSTORAGE';
export const TODO_CONTENT='TODO_CONTENT';
export const DELETE_TODOFROMSTORAGE='DELETE_TODOFROMSTORAGE';
